support/Makefile.devel: Allow huge number of interfaces

diff --git a/support/Makefile.devel b/support/Makefile.devel
--- a/support/Makefile.devel
+++ b/support/Makefile.devel
@@ -177,12 +177,29 @@ tmp/%.mod.fc: tmp/m4support.m4f %.fc
 	$(verbose) $(SEMOD_PKG) -o $@ -m $< -f $<.fc
 
 tmp/iferror.m4:
-	@echo "ifdef(\`__if_error',\`m4exit(1)')" > tmp/iferror.m4
+	@echo "ifdef(\`__if_error',\`m4exit(1)')" > $@
+
+# Make fails if there is too many args for a command
+define multi_arg_command =
+        $(1) $(wordlist      1, 1000,$(3)) > $(2)
+        if [ "$(wordlist  1001, 2000,$(3))" ]; then $(1) $(wordlist  1001, 2000,$(3)) >> $(2); fi
+        if [ "$(wordlist  2001, 3000,$(3))" ]; then $(1) $(wordlist  2001, 3000,$(3)) >> $(2); fi
+        if [ "$(wordlist  3001, 4000,$(3))" ]; then $(1) $(wordlist  3001, 4000,$(3)) >> $(2); fi
+        if [ "$(wordlist  4001, 5000,$(3))" ]; then $(1) $(wordlist  4001, 5000,$(3)) >> $(2); fi
+        if [ "$(wordlist  5001, 6000,$(3))" ]; then $(1) $(wordlist  5001, 6000,$(3)) >> $(2); fi
+        if [ "$(wordlist  6001, 7000,$(3))" ]; then $(1) $(wordlist  6001, 7000,$(3)) >> $(2); fi
+        if [ "$(wordlist  7001, 8000,$(3))" ]; then $(1) $(wordlist  7001, 8000,$(3)) >> $(2); fi
+        if [ "$(wordlist  8001, 9000,$(3))" ]; then $(1) $(wordlist  8001, 9000,$(3)) >> $(2); fi
+        if [ "$(wordlist  9001,10000,$(3))" ]; then $(1) $(wordlist  9001,10000,$(3)) >> $(2); fi
+        if [ "$(wordlist 10001,11000,$(3))" ]; then exit 1; fi
+endef
 
 tmp/all_interfaces.conf: | tmp
 tmp/all_interfaces.conf: tmp/m4support.m4f $(header_interfaces) $(detected_ifs) tmp/iferror.m4
 	@echo "divert(-1)" > $@
-	$(verbose) $(M4) -R $^ | sed -e s/dollarsstar/\$$\*/g >> $@
+	$(call multi_arg_command,cat,$@.tmp,$(detected_ifs))
+	$(verbose) cat -- $(header_interfaces) $@.tmp tmp/iferror.m4 | $(M4) -R tmp/m4support.m4f - | sed -e s/dollarsstar/\$$\*/g >> $@
+	@rm -f -- $@.tmp
 	@echo "divert" >> $@
 
 # so users dont have to make empty .fc and .if files
